/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.findram;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.LambdaLogger;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import dev.findram.services.SnsService;
import dev.findram.services.WeatherService;

import java.util.Map;


public class LambdaHandler implements RequestHandler<Map<String,String>, String> {
    public final WeatherService weatherService;
    public final SnsService snsService;

    public LambdaHandler(WeatherService weatherService, SnsService snsService){
        this.weatherService = weatherService;
        this.snsService = snsService;

    }

    @Override
    public String handleRequest(Map<String,String> event, Context context)
    {
        LambdaLogger logger = context.getLogger();

        try {
            var forecast = weatherService.getForecastForLatLon(-35.2809, 149.1300);
            var willRain = weatherService.checkForRainInNextNHours(forecast, 14);

            if (willRain) {
//                snsService.publish();

                return "{\"status\": 200, \"body\": \"Success. Text message sent to all subscribers via SMS.\"}";
            }
            snsService.publish();

            return "{\"status\": 200, \"body\": \"No rain forecast. No action required.\"}";

        } catch (Exception e) {
            logger.log(e.toString());
            return "Error: " + e;
        }

    }
}