/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.findram;

import com.amazonaws.services.lambda.runtime.Context;
import dev.findram.helpers.TestContext;
import org.junit.jupiter.api.Test;

import java.util.Map;

import static java.util.Map.entry;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class LambdaHandlerTest {
    @Test void appHasAGreeting() {
        LambdaHandler classUnderTest = new LambdaHandler();

        assertNotNull(classUnderTest.handleRequest(
                Map.ofEntries(
                        entry("foo","bar")
                ),
                new TestContext()
        ));
    }
}
