/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.findram;

import dev.findram.entities.HourlyForecast;
import dev.findram.helpers.TestContext;
import dev.findram.entities.WeatherForecast;
import dev.findram.services.WeatherService;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.io.IOException;
import java.util.Map;

import static java.util.Map.entry;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.anyDouble;

class LambdaHandlerTest {

    @Test void handlerExecutesWithoutError() throws IOException, InterruptedException {
        var mockReturn = new WeatherForecast(
                123,
                123,
                "gmt",
                new HourlyForecast[]{});

        WeatherService spyWeatherService = Mockito.spy(new WeatherService());
        Mockito.doReturn(mockReturn).when(spyWeatherService).getForecastForLatLon(anyDouble(), anyDouble());

        LambdaHandler lambdaHandler = new LambdaHandler(spyWeatherService);

        assertNotNull(lambdaHandler.handleRequest(
                Map.ofEntries(
                        entry("foo","bar")
                ),
                new TestContext()
        ));
    }
}
